spring:
  datasource:
    hikari:
      max-lifetime: 1800000 # (ms), default
      connection-timeout: 10000
      validation-timeout: 10000
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/demo?reWriteBatchedInserts=true
      username: taesu
      password: password
      maximum-pool-size: ${app.platform-backend.storage.jpa.datasource.hikari.maximum-pool-size:10}
      pool-name: platform-master
    url: ${spring.datasource.hikari.jdbc-url}
    driver-class-name: ${spring.datasource.hikari.driver-class-name}
logging:
  level:
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
