spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate.envers.audit_table_suffix: _HIS
      org.hibernate.envers.modified_flag_suffix: _CHANGED
      org.hibernate.envers.modified_column_naming_strategy: improved
      org.hibernate.envers.store_data_at_delete: true
      hibernate.envers.autoRegisterListeners: false
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.default_batch_fetch_size: 1000
      hibernate.jdbc.fetch_size: ${spring.jdbc.template.fetch-size}
      hibernate.check_nullability: true # @NotNull 검사
      hibernate.hbm2ddl.auto: validate # @Column(nullable) 검사
    open-in-view: false
  jdbc:
    template:
      fetch-size: 150
  datasource:
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.default_batch_fetch_size: 1000
      hibernate.jdbc.fetch_size: ${spring.jdbc.template.fetch-size}
